$(document).ready(function(){
  $(".hide").hide();
  
  $(".marker-a").click(function(){
    $(".hide").hide();
    $(".a-txt").fadeIn(300);
  });
  
 $(".marker-b").click(function(){
    $(".hide").hide();
    $(".b-txt").fadeIn(300);
  });
  
$(".marker-с").click(function(){
    $(".hide").hide();
    $(".с-txt").fadeIn(300);
  });
  
    $(".marker-brazil").click(function(){
       $(".hide").hide();
    $(".brazil-txt").fadeIn(300);
  });
  $(".marker-d").click(function(){
    $(".hide").hide();
    $(".d-txt").fadeIn(300);
  });
  $(".marker-e").click(function(){
    $(".hide").hide();
    $(".e-txt").fadeIn(300);
  });
  $(".marker-f").click(function(){
    $(".hide").hide();
    $(".f-txt").fadeIn(300);
  });
  $(".marker-g").click(function(){
    $(".hide").hide();
    $(".g-txt").fadeIn(300);
  });
  $(".marker-h").click(function(){
    $(".hide").hide();
    $(".h-txt").fadeIn(300);
  });
    $(".marker-i").click(function(){
    $(".hide").hide();
    $(".i-txt").fadeIn(300);
  });
   $(".marker-j").click(function(){
    $(".hide").hide();
    $(".j-txt").fadeIn(300);
  });
     $(".marker-k").click(function(){
    $(".hide").hide();
    $(".k-txt").fadeIn(300);
  });
       $(".marker-m").click(function(){
    $(".hide").hide();
    $(".m-txt").fadeIn(300);
  });
         $(".marker-l").click(function(){
    $(".hide").hide();
    $(".l-txt").fadeIn(300);
  });
           $(".marker-n").click(function(){
    $(".hide").hide();
    $(".n-txt").fadeIn(300);
  });
   $(".marker-o").click(function(){
    $(".hide").hide();
    $(".o-txt").fadeIn(300);
  });
     $(".marker-p").click(function(){
    $(".hide").hide();
    $(".p-txt").fadeIn(300);
  });
  $(".marker-q").click(function(){
    $(".hide").hide();
    $(".q-txt").fadeIn(300);
  });
  $(".marker-r").click(function(){
    $(".hide").hide();
    $(".r-txt").fadeIn(300);
  });
    $(".marker-s").click(function(){
    $(".hide").hide();
    $(".s-txt").fadeIn(300);
  });
      $(".marker-t").click(function(){
    $(".hide").hide();
    $(".t-txt").fadeIn(300);
  });
        $(".marker-u").click(function(){
    $(".hide").hide();
    $(".u-txt").fadeIn(300);
  });
          $(".marker-v").click(function(){
    $(".hide").hide();
    $(".v-txt").fadeIn(300);
  });
  $(".marker-isc").click(function(){
    $(".hide").hide();
    $(".isc-txt").fadeIn(300);
  });
});